#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6747927222                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Weather simplified

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                 
your_link                                 :           
your_city                                 :                            
email_address                             : 
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : User Friendly
    description                           : Easily scroll and view all the forecasts without any interuptions.
    
  - title                                 : Hourly Conditions
    description                           : View conditions like temperature, humidity, and more down to the hour and up to 24 hours in advance. 

  - title                                 : Daily Conditions
    description                           : Plan ahead by viewing daily forecasts up to 10 days in advance. View the forecast summary for each day which includes precipitation amounts and more.  

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#121212"
topbar_transparency                       : 1.0
topbar_title_color                        : "#FEFFFF"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#222224"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#EFEFEF"

link_color                                : "#1d63ea"

app_title_color                           : "#FEFFFF"
app_price_color                           : "#FEFFFF"
app_description_color                     : "#FEFFFF"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#121212"
feature_icons_background_color            : "#EFEFEF"

social_icons_foreground_color             : "#121212"
social_icons_background_color             : "#EFEFEF"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
